"""make_subscription_merchant_id_nullable

Revision ID: 4974088f51cf
Revises: 92e1c4e541e9
Create Date: 2026-07-21 13:27:30.659498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4974088f51cf'
down_revision: Union[str, Sequence[str], None] = '92e1c4e541e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'merchant_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'merchant_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
