"""add_status_to_subscription_plans_and_fix_types

Revision ID: 59222c1319bd
Revises: 703f5e4dcb67
Create Date: 2026-07-07 00:24:29.396361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59222c1319bd'
down_revision: Union[str, Sequence[str], None] = '703f5e4dcb67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Шаг 1: Добавляем колонку, разрешая NULL
    op.add_column(
        'subscription_plans',
        sa.Column(
            'status',
            sa.Enum('active', 'archived', 'deprecated', name='planstatus', native_enum=False),
            nullable=True
        )
    )

    # Шаг 2: Проставляем статус 'active' для всех уже существующих тарифов
    op.execute("UPDATE subscription_plans SET status = 'active'")

    # Шаг 3: Теперь, когда пустых ячеек не осталось, спокойно делаем колонку NOT NULL
    op.alter_column('subscription_plans', 'status', nullable=False)

    # Дальше оставляем автоматически сгенерированный индекс без изменений
    op.create_index(op.f('ix_subscription_plans_status'), 'subscription_plans', ['status'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'status',
               existing_type=sa.Enum('trial', 'active', 'payment_pending', 'canceled', 'expired', name='subscriptionstatus', native_enum=False),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.drop_index(op.f('ix_subscription_plans_status'), table_name='subscription_plans')
    op.drop_column('subscription_plans', 'status')
    # ### end Alembic commands ###
