"""add_auto_renew_to_subscriptions

Revision ID: 9c807f9a3c39
Revises: 59222c1319bd
Create Date: 2026-07-18 22:59:27.635564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c807f9a3c39'
down_revision: Union[str, Sequence[str], None] = '59222c1319bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('auto_renew', sa.Boolean(), nullable=True))
    op.alter_column('subscriptions', 'status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('trial', 'active', 'payment_pending', 'canceled', 'expired', 'past_due', name='subscriptionstatus', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'status',
               existing_type=sa.Enum('trial', 'active', 'payment_pending', 'canceled', 'expired', 'past_due', name='subscriptionstatus', native_enum=False),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.drop_column('subscriptions', 'auto_renew')
    # ### end Alembic commands ###
